# Generated by Django 6.0.3 on 2026-03-16 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Tên điểm giao hàng hoặc Kho', max_length=100)),
                ('x', models.FloatField(help_text='Tọa độ X')),
                ('y', models.FloatField(help_text='Tọa độ Y')),
                ('is_depot', models.BooleanField(default=False, help_text='Đánh dấu đây là điểm xuất phát (Kho)')),
            ],
        ),
        migrations.CreateModel(
            name='RoutePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Tên hoặc mô tả tuyến đường', max_length=200)),
                ('total_distance', models.FloatField(default=0.0, help_text='Tổng khoảng cách của tuyến')),
                ('is_optimized', models.BooleanField(default=False, help_text='Đánh dấu tuyến này là kết quả từ thuật toán TSP')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RouteStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_order', models.IntegerField(help_text='Thứ tự dừng của điểm này trong tuyến')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.location')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='core.routeplan')),
            ],
            options={
                'ordering': ['stop_order'],
            },
        ),
    ]
