# Generated by Django 6.0.3 on 2026-03-16 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['-is_depot', 'name']},
        ),
        migrations.RemoveField(
            model_name='location',
            name='x',
        ),
        migrations.RemoveField(
            model_name='location',
            name='y',
        ),
        migrations.AddField(
            model_name='location',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='latitude',
            field=models.FloatField(default=0.0, help_text='Vĩ độ (latitude) - tọa độ bắc/nam'),
        ),
        migrations.AddField(
            model_name='location',
            name='longitude',
            field=models.FloatField(default=0.0, help_text='Kinh độ (longitude) - tọa độ đông/tây'),
        ),
    ]
